-- Record the exact legal versions acted on during account creation.
--
-- The browser supplies only affirmative actions and version identifiers. The
-- authoritative timestamps are generated by PostgreSQL, and the record lives
-- in a non-exposed schema with no client write path. The auth.users trigger is
-- deliberately strict: if validation or persistence fails, the surrounding
-- user-creation transaction fails instead of leaving an unrecorded account.

BEGIN;

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC, anon, authenticated;

CREATE TABLE private.user_legal_actions (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  terms_version text NOT NULL,
  privacy_version text NOT NULL,
  terms_accepted_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
  privacy_acknowledged_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
  PRIMARY KEY (user_id, terms_version, privacy_version),
  CONSTRAINT user_legal_actions_terms_version_check CHECK (
    terms_version = btrim(terms_version)
    AND char_length(terms_version) BETWEEN 1 AND 64
  ),
  CONSTRAINT user_legal_actions_privacy_version_check CHECK (
    privacy_version = btrim(privacy_version)
    AND char_length(privacy_version) BETWEEN 1 AND 64
  )
);

COMMENT ON TABLE private.user_legal_actions IS
  'Immutable application audit record of versioned Terms acceptance and Privacy Notice acknowledgement.';
COMMENT ON COLUMN private.user_legal_actions.terms_accepted_at IS
  'Server-generated time at which the current Terms version was accepted.';
COMMENT ON COLUMN private.user_legal_actions.privacy_acknowledged_at IS
  'Server-generated time at which the current Privacy Notice version was acknowledged.';

ALTER TABLE private.user_legal_actions ENABLE ROW LEVEL SECURITY;

-- No Data API role can read or mutate the audit record. The service role gets
-- read-only access for controlled compliance exports; only PostgreSQL owners
-- can intentionally alter records during an audited administrative migration.
REVOKE ALL ON TABLE private.user_legal_actions
  FROM PUBLIC, anon, authenticated, service_role, supabase_auth_admin;
GRANT USAGE ON SCHEMA private TO service_role, supabase_auth_admin;
GRANT SELECT ON TABLE private.user_legal_actions TO service_role;

CREATE OR REPLACE FUNCTION private.record_initial_signup_legal_actions()
RETURNS trigger
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  current_terms_version CONSTANT text := '2026-07-18';
  current_privacy_version CONSTANT text := '2026-07-18';
BEGIN
  IF NEW.raw_user_meta_data -> 'terms_accepted' IS DISTINCT FROM 'true'::jsonb THEN
    RAISE EXCEPTION 'Current Terms of Service acceptance is required'
      USING ERRCODE = '23514';
  END IF;

  IF NEW.raw_user_meta_data -> 'privacy_acknowledged' IS DISTINCT FROM 'true'::jsonb THEN
    RAISE EXCEPTION 'Current Privacy Notice acknowledgement is required'
      USING ERRCODE = '23514';
  END IF;

  IF NEW.raw_user_meta_data ->> 'terms_version'
     IS DISTINCT FROM current_terms_version THEN
    RAISE EXCEPTION 'The current Terms of Service version must be accepted'
      USING ERRCODE = '23514';
  END IF;

  IF NEW.raw_user_meta_data ->> 'privacy_version'
     IS DISTINCT FROM current_privacy_version THEN
    RAISE EXCEPTION 'The current Privacy Notice version must be acknowledged'
      USING ERRCODE = '23514';
  END IF;

  INSERT INTO private.user_legal_actions (
    user_id,
    terms_version,
    privacy_version
  )
  VALUES (
    NEW.id,
    current_terms_version,
    current_privacy_version
  );

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.record_initial_signup_legal_actions()
  FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION private.record_initial_signup_legal_actions()
  TO supabase_auth_admin;

CREATE TRIGGER record_initial_signup_legal_actions_after_user_insert
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION private.record_initial_signup_legal_actions();

COMMIT;
